apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - image: scheele/udacity-frontend
        name: frontend
        ports:
        - containerPort: 8100
        resources: {}
        env:
        - name: API_HOST
          value: reverseproxy:8080 
      restartPolicy: Always
status: {}
